# Harmony Jekyll theme general configurations 

# Base URL
baseurl: /SICP 

# Site live URL
url: http://gummary.github.io

harmony:
  name: SICP习题集 
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Gummary 
    email: sdythp@gmail.com
    url: blog.gummary.xyz

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github:     gummary 
    twitter:    gummary_ 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
